sudo: false


language: python


python:
    - 3.5
    - nightly


os:
    - linux
#    - osx


before_install: pip install --upgrade pip setuptools wheel anglerfish --quiet


install: true


before_script: pyclean --verbose .


script:
    - wget https://code.jquery.com/jquery-git2.js
    - chmod +x $TRAVIS_BUILD_DIR/css-html-js-minify.py
    - $TRAVIS_BUILD_DIR/css-html-js-minify.py --prefix temp_ --timestamp --hash --beep $TRAVIS_BUILD_DIR/jquery-git2.js
    - wget https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.css
    - $TRAVIS_BUILD_DIR/css-html-js-minify.py --prefix temp_ --timestamp --wrap --hash $TRAVIS_BUILD_DIR/bootstrap.css
    - pip install --upgrade --no-compile css-html-js-minify


after_script: true


after_success: true


after_failure: true


notifications:
    email:
        recipients: juancarlospaco@gmail.com
        on_success: change
        on_failure: always


cache: apt
